### ISSUE TITLE
Research & compare RPC crates

### ISSUE THREAD

**Issue by Wodann** [NomicFoundation/rethnet#10]
To perform RPC calls, we need to choose a crate. There should be several options within the ecosystem Things to consider when comparing:

- Must be actively maintained
- Must be performant
- Should be safe; i.e. little to no `unsafe` code and/or audited
- Nice to have support for a JSON+RPC server - as we'll likely add one to Rethnet in the future

The output of this task should be a comparison of the different options and a preference for which crate to integrate in Rethnet.

**Comment by feuGeneA** [comment]
I tried a few different crates, and none seemed to fit the criteria outlined here.

But, what I found is that we don't really need a library.

As suggested, I'm simply using `reqwest` to make the calls, and composing the request body with a string literal (with some substitutions for input values), and that doesn't require any library at all. At some level, I'd like to see some client-side validation of the request before it's submitted, but given that it's not totally straightforward, and given that the server effectively performs validation for us, that client-side validation seems unnecessary.

As far as interpretation of the response, we do need some custom types for that, but I was able to achieve that by simply copying ~80 lines of code from github.com/koushiro/async-jsonrpc (which works great but is not actively maintained).

Perhaps we may want something more robust for _serving_ RPC calls, but when we're just acting as a client I think the simple approach I took in nomicfoundation/hardhat#3383 is just fine.
