### ISSUE TITLE
Integrate cargo-hack in CI

### ISSUE THREAD

**Issue by Wodann** [NomicFoundation/rethnet#168]
The way cargo resolves dependencies prevents us to run `cargo check` with `--no-default-features` for all crates. To circumvent this, we need an alternative. See https://github.com/rust-lang/cargo/issues/12470 for more details.

**Definition of Done**
Integrate [cargo-hack](https://crates.io/crates/cargo-hack) into the CI and resolve potential compiler errors

**Comment by agostbiro** [comment]
Done in https://github.com/NomicFoundation/hardhat/pull/4380
