### ISSUE TITLE
Clippy custom rules not applied in CI

### ISSUE THREAD

**Issue by agostbiro** [NomicFoundation/rethnet#174]
**Problem**

The custom Clippy rules aren't taken into account in the CI and on MacOS locally:

https://github.com/NomicFoundation/hardhat/blob/3fbf3ffb4732e4ed37a7285bb542d90cd95eaaaa/.cargo/config

**Definition of Done**

The custom Clippy rules are taken into account in the CI and on MacOS locally.

**Comment by agostbiro** [comment]
When running the pre-commit hook clippy succeeds, but when running `cargo clippy --all --all-targets --all-features -- -D warnings` from the repo root it fails.

**Comment by Wodann** [comment]
Very odd..

**Comment by agostbiro** [comment]
Done in https://github.com/NomicFoundation/hardhat/pull/4364
