### ISSUE TITLE
Research: trace execution in Rethnet

### ISSUE THREAD

**Issue by fvictorio** [NomicFoundation/rethnet#21]
This issue is about designing how to start tracing executions with Rethnet.

There are at least two parts to this effort:

- Tracing the execution of each new tx (what is now done with the `VMTracer`)
- Tracing an old execution through `debug_traceTransaction` (now done with the `VMDebugTracer`)

The first itaration of this will probably keep those classes and just use callbacks from Rethnet.

**Comment by Wodann** [comment]
#14 for the `VMTracer`
#52 for the `VMDebugTracer`
