### ISSUE TITLE
Research: mempool in Rethnet

### ISSUE THREAD

**Issue by fvictorio** [NomicFoundation/rethnet#22]
We can probably implement the mempool in Rethnet right now. This issue is about defining exactly what that would mean, the required API and functionality, and what are the validation requirements. We should also consider doing a "dual execution" approach here too.

**Comment by Wodann** [comment]
https://www.notion.so/nomicfoundation/Rethnet-Architecture-a1aee02925c94d9dbbfe6ed60b34ba59
