### ISSUE TITLE
Research: tx, block and blockchain models

### ISSUE THREAD

**Issue by fvictorio** [NomicFoundation/rethnet#23]
Assuming we have the RethnetAdapter fully implemented, what are the next steps? What are these abstractions going to look like? Should we have a "dual execution" strategy here and, if so, how? What kind of validations are necessary?

This issue is mainly meant to be a starting point, we should close it in favor of other, better defined issues when we have a better understanding of how we'll approach this.

**Comment by Wodann** [comment]
https://www.notion.so/nomicfoundation/Rethnet-Architecture-a1aee02925c94d9dbbfe6ed60b34ba59
