### ISSUE TITLE
Implement `napi` bindings for `ForkState`

### ISSUE THREAD

**Issue by Wodann** [NomicFoundation/rethnet#30]
Implement napi bindings for creating a Rethnet state with a forked database.

This might require some additional changes to the API to ensure that users of Rethnet can create a state manager from - what's currently called - a `LayeredDatabase` as well as the new `ForkedDatabase`.

**Depends on**
- [x] #9

**Comment by feuGeneA** [comment]
There's already a database that's exposed to napi, LayeredDatabase. I can basically mimic the logic of that. There's a state manager using a layered database, I can look at that, we want me to use the state manager class as well, but ensure that i'm using the trait type inside of a box. state manager .rs contains a dataabase that's a runtime object, with various constructors, including an napi factory which needs to be created for the fork database. there's already one for the layered database, need one for the forked database, that'll construct that database and initialize the runtime object. end with "self::with_db()". "#[napi_object]" structs required for conversion from javascript types. see napi.rs for more explanations of what can be converted. see examples of conversions in that state.rs, like from BigInt, Buffer, etc.

**Comment by Wodann** [comment]
You can use `yarn test:forking` to run all forking tests.
