### ISSUE TITLE
Research impact of removing ethereumjs-vm

### ISSUE THREAD

**Issue by Wodann** [NomicFoundation/rethnet#39]
This will inform all necessary tasks to complete: #7

**Comment by fvictorio** [comment]
The two most important things to adapt are the VMDebugTracer (opened issue #52 for this) and the `runFullBlock` script (opened #53 for this).

I'm going to close this one now. There might be hidden things we still need to fix for a complete, rethnet-only execution in all cases, but I think we'll figure those out when we actually do it.
