### ISSUE TITLE
Implement read-only `struct RemoteDatabase` for querying the blockchain

### ISSUE THREAD

**Issue by Wodann** [NomicFoundation/rethnet#49]
A `struct RemoteDatabase` that implements `trait DatabaseRef` using the JSON+RPC client to query Ethereum's state.

**Depends on**
#27

**Comment by feuGeneA** [comment]
Notes from a call discussing this issue:

The `DatabaseRef` trait is in `revm`, and we're re-exporting it from `rethnet_evm`. In the `db` folder, under `src`, there's already a `layered_db.rs file, and I can just add a new file for the remote database, and do something similar to what the layered db is doing, just implement traits, except that the layered one is read/write and this one will be read only.

My client code is async, so it will be a little tricky, but there's an example of how to block within a task for a synchronous call in `db/sync.rs`.
