### ISSUE TITLE
Use VMAdapter in the `runFullBlock` script

### ISSUE THREAD

**Issue by fvictorio** [NomicFoundation/rethnet#53]
This script is used in the CI to fork mainnet at block N, run all the txs in block N+1, and assert that the result is the same as the one in mainnet. Obviously this needs forking support in rethnet.

This is also important to further validate the implementation.

**Comment by Wodann** [comment]
Does that mean that we do need forking to release Rethnet v0.1.0?

**Comment by fvictorio** [comment]
I think this can wait until v0.2.0.
