### ISSUE TITLE
Add on-disk caching for RemoteDatabase

### ISSUE THREAD

**Issue by Wodann** [NomicFoundation/rethnet#64]
Doesn't need to be backwards compatible with what Hardhat currently does.

One possible approach is to:
- implement `serde::{Deserialize, Serialize}` for the key and value of our cached remote database; and
- use a binary (de)serializer to write/read to disk

**Comment by feuGeneA** [comment]
Pato suggested https://docs.rs/rkv/latest/rkv/ at https://nomicfoundation.slack.com/archives/C03UN893ZT4/p1676049222227029
