### ISSUE TITLE
Use remote node cache in CI workflow

### ISSUE THREAD

**Issue by Wodann** [NomicFoundation/rethnet#87]
**Definition of Done**
- The `hardhat-core` GitHub CI workflow is retaining Rethnet's remote node cache for the "test-fork" job across CI runs.
- As this is still in a testing phase, it should be set up as a separate job in the workflow

BEWARE: currently the cache does not properly handle requests for "latest". Caching of these should be avoided as latest is continuously changing. See #88

**Comment by agostbiro** [comment]
Fixed in https://github.com/NomicFoundation/hardhat/pull/4376
