### ISSUE TITLE
Cache per chain ID instead of per provider

### ISSUE THREAD

**Issue by Wodann** [NomicFoundation/rethnet#99]
**Problem**

The [`send_request_body`](https://github.com/NomicFoundation/hardhat/blob/rethnet/main/crates/rethnet_eth/src/remote/client.rs#L132) function uses an on-disk caching mechanism that uses a hash of the request body as index into the cache.

Currently, the client caches requests in file hierarchy like this:

<hash of provider A's URL (incl. token)>
 |__ <hash of request 1>
 |__ <hash of request 2>

<hash of provider B's URL (incl. token)>
|__ <hash of request 1>
|__ <hash of request 2>
 
If we change providers or update our token, this means that our entire on-disk cache will be invalidated, even if our chain ID remains the same.

We can avoid this by using the chain ID instead.

**Definition of Done**
Prevent caching of JSON-RPC requests per provider URL - as it currently is - and instead cache per chain ID.

**Comment by agostbiro** [comment]
Done in https://github.com/NomicFoundation/hardhat/pull/4270
